#!/usr/bin/env python
#
# Glances - An eye on your system
#
# SPDX-FileCopyrightText: 2024 Nicolas Hennion <nicolas@nicolargo.com>
#
# SPDX-License-Identifier: LGPL-3.0-only
#

"""Tests for the CPU chart feature (part of the CPU plugin)."""

import pytest


@pytest.fixture
def cpu_plugin(glances_stats):
    """Return the CPU plugin instance, which owns the chart feature."""
    return glances_stats.get_plugin('cpu')


class TestCpuChartBasics:
    """Test that the CPU plugin exposes the chart feature."""

    def test_plugin_name(self, cpu_plugin):
        """Test plugin name is correctly set."""
        assert cpu_plugin.plugin_name == 'cpu'

    def test_plugin_is_enabled(self, cpu_plugin):
        """Test that the plugin is enabled by default."""
        assert cpu_plugin.is_enabled() is True

    def test_display_curse_enabled(self, cpu_plugin):
        """Test that curse display is enabled."""
        assert cpu_plugin.display_curse is True

    def test_chart_helper_attached(self, cpu_plugin):
        """Test that the CpuChart helper is attached to the plugin."""
        assert hasattr(cpu_plugin, '_chart')

    def test_msg_curse_chart_method_exists(self, cpu_plugin):
        """Test that the plugin exposes msg_curse_chart."""
        assert callable(getattr(cpu_plugin, 'msg_curse_chart', None))

    def test_history_tracks_total(self, cpu_plugin):
        """Test that history is configured to track total CPU usage for the chart sparkline."""
        items = cpu_plugin.get_items_history_list()
        assert items is not None
        item_names = [item['name'] for item in items]
        assert 'total' in item_names


class TestCpuChartData:
    """Test that the CPU plugin collects all data needed by the chart."""

    def test_update_contains_percpu(self, cpu_plugin):
        """Test that update collects per-core data."""
        cpu_plugin.update()
        stats = cpu_plugin.get_raw()
        assert 'percpu' in stats
        assert isinstance(stats['percpu'], list)

    def test_percpu_entries_have_required_keys(self, cpu_plugin):
        """Test that each per-core entry has cpu_number and total."""
        cpu_plugin.update()
        for core in cpu_plugin.get_raw().get('percpu', []):
            assert 'cpu_number' in core
            assert 'total' in core

    def test_update_contains_cpu_name(self, cpu_plugin):
        """Test that CPU model name is collected."""
        cpu_plugin.update()
        stats = cpu_plugin.get_raw()
        assert 'cpu_name' in stats

    def test_update_contains_frequency_fields(self, cpu_plugin):
        """Test that frequency fields are present (may be None on some platforms)."""
        cpu_plugin.update()
        stats = cpu_plugin.get_raw()
        assert 'cpu_hz_current' in stats
        assert 'cpu_hz' in stats

    def test_logical_core_count_valid(self, cpu_plugin):
        """Test that logical core count is at least 1."""
        cpu_plugin.update()
        log_cores = cpu_plugin.get_raw().get('cpu_log_core')
        if log_cores is not None:
            assert log_cores >= 1

    def test_physical_core_count_valid(self, cpu_plugin):
        """Test that physical core count is at least 1."""
        cpu_plugin.update()
        phys_cores = cpu_plugin.get_raw().get('cpu_phys_core')
        if phys_cores is not None:
            assert phys_cores >= 1

    def test_process_count_non_negative(self, cpu_plugin):
        """Test that process count is non-negative."""
        cpu_plugin.update()
        processes = cpu_plugin.get_raw().get('processes')
        if processes is not None:
            assert processes >= 0

    def test_thread_count_non_negative(self, cpu_plugin):
        """Test that thread count is non-negative."""
        cpu_plugin.update()
        threads = cpu_plugin.get_raw().get('threads')
        if threads is not None:
            assert threads >= 0

    def test_chart_max_cpu_display_set(self, cpu_plugin):
        """Test that chart_max_cpu_display config value is loaded."""
        assert hasattr(cpu_plugin, '_chart_max_cpu_display')
        assert cpu_plugin._chart_max_cpu_display >= 1


class TestCpuChartDisplay:
    """Test the chart display output generated by msg_curse_chart."""

    def test_msg_curse_chart_returns_list(self, cpu_plugin):
        """Test that msg_curse_chart returns a list."""
        cpu_plugin.update()
        msg = cpu_plugin.msg_curse_chart(max_width=80)
        assert isinstance(msg, list)

    def test_msg_curse_chart_entries_are_dicts(self, cpu_plugin):
        """Test that msg_curse_chart entries are properly formatted dicts."""
        cpu_plugin.update()
        msg = cpu_plugin.msg_curse_chart(max_width=80)
        if msg:
            for entry in msg:
                assert isinstance(entry, dict)
                assert 'msg' in entry

    def test_msg_curse_chart_has_cpu_title(self, cpu_plugin):
        """Test that msg_curse_chart output contains a CPU-related title."""
        cpu_plugin.update()
        msg = cpu_plugin.msg_curse_chart(max_width=80)
        if msg:
            messages = [m.get('msg', '') for m in msg]
            assert any('CPU' in str(m) for m in messages)

    def test_msg_curse_chart_empty_without_max_width(self, cpu_plugin):
        """Test that msg_curse_chart returns empty list when max_width is not provided."""
        cpu_plugin.update()
        msg = cpu_plugin.msg_curse_chart()
        assert msg == []


class TestCpuChartFieldsDescription:
    """Test that chart fields are included in the CPU plugin's fields_description."""

    def test_chart_fields_described(self, cpu_plugin):
        """Test that chart-specific fields have descriptions."""
        chart_fields = ['cpu_name', 'cpu_hz_current', 'cpu_hz', 'cpu_log_core', 'cpu_phys_core',
                        'processes', 'threads']
        for field in chart_fields:
            assert field in cpu_plugin.fields_description, f"Missing field description for: {field}"

    def test_each_field_has_description_key(self, cpu_plugin):
        """Test that each field entry contains a description string."""
        for field, info in cpu_plugin.fields_description.items():
            assert 'description' in info, f"Field '{field}' missing description key"
